---
#-------------------------------
# General Site Settings

title: Mezze
logo:
author: Chris Jong-min Choi
description: this is meta description
email: cjm064@naver.com
phone: +82 10 4911 6794
address: 
copyright: Copyright &copy; 2020 Designed by)

menu:
  - { name: About, link: "/about" }
  - { name: Blog, link: "/blog" }
  - { name: Archive, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Hero Section

hero:
  hero-title: í˜¼ì €ì˜µì„œì˜ˆ! <br> Greetings! <br> Kia ora!



#-------------------------------

# About (Section and Page)

# About Section
blurb: ë°˜ê°‘ìŠµë‹ˆë‹¤.<br>MezzeëŠ” ê·¸ë¦¬ìŠ¤, í„°í‚¤ ì§€ë°©ì—ì„œ ì• í”¼íƒ€ì´ì €ë¡œ ì œê³µë˜ëŠ” ì‘ì€ ìš”ë¦¬ì…ë‹ˆë‹¤.<br>ë•Œë¡œëŠ” ì• í”¼íƒ€ì´ì €ì²˜ëŸ¼ ê°€ë³ê²Œ, ë•Œë¡œëŠ” ì‹ì‚¬ë¡œì„œ ì¦ê¸¸ ìˆ˜ ìˆëŠ” ë¸”ë¡œê·¸ë¡œ ì¦ê²¨ì£¼ì…¨ìœ¼ë©´ í•©ë‹ˆë‹¤.
blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page
content: 
# Work Process Section
work-process:
  - title: "Computer Education"
    icon: "assets/images/icons/jnu.png"
    content: "Major"

  - title: "Big Data Convergence"
    icon: "assets/images/icons/jnu.png"
    content: "Minor"

  - title: "TEDXJNUHighSchool"
    icon: "assets/images/tedx.jpg"
    content: "Advisor"

 
education-title: Education
education:
  - {
      name: Bachelor of Science in Computer Education,
      date: "March 2020 - Present",
      organization: "Jeju National University",
    }
  - {
      name: Minor of Big Data Convergence,
      date: "March 2022 - Present",
      organization: "Jeju National University",
    }
  - {
      name: Kakao Track,
      date: "August 2022 - Present",
      organization: "Jeju National University, KaKao",
    }
  - {
      name: English Language for Software Engineering,
      date: "July 2022 â€“ August 2022",
      organization: "Auckland University of Technology",
    }


# Skills Section

skills-title: Skills
skills:
  - { name: C, color: "#fdb157", value: "20%" }
  - { name: Python, color: "#9473e6", value: "40%" }
  - { name: Java, color: "#9473e6", value: "40%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: Mentor<br>(AI hackathon Program),
      icon: "ğŸ«",
      date: "October 2022",
      organization: "Jeju National University Intelligent Software Education Research Institute. <br> Jeju Province. <br> Jeju National University.",
    }
  - {
      name: Assistant Instructor<br>(High School-University linkage Program),
      icon: "ğŸ«",
      date: "April 2022 â€“ July 2022",
      organization: "Jeju National University Intelligent Software Education Research Institute",
    }
  - {
      name: Team Leader<br>(Industry-Academic Cooperation Project),
      icon: "ğŸš©",
      date: "March 2022 - August 2022",
      organization: "SW-Centered University of Jeju National University",
    }
  - {
      name: Lead Organizer<br>(TEDxJNUHighSchool),
      icon: "ğŸš©",
      date: "September 2017 - December 2018",
      organization: "TEDxJNUHighSchool",
    }
  - {
      name: Advisor<br>(TEDxJNUHighSchool),
      icon: "ğŸ“–",
      date: "December 2018 - Present",
      organization: "TEDxJNUHighSchool",
    }
  - {
      name: Mentor<br>(Jeju Social Welfare Center ChildFund Korea),
      icon: "ğŸ«",
      date: "April 2022 â€“ October 2022",
      organization: "Jeju Social Welfare Center ChildFund Korea",
    }
  - {
      name: Mentor<br>(SW Innovation Lecture),
      icon: "ğŸ«",
      date: "September 2022 -December 2022",
      organization: "Jeju National University",
    }
   - {
      name: Mentor<br>(Multimedia),
      icon: "ğŸ«",
      date: "March 2023 - Present",
      organization: "Jeju National University",
    }   
#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Bachelor of Science in Computer Education,
      date: "March 2020 - Present",
      organization: "Jeju National University",
    }
  - {
      name: Minor of Big Data Convergence,
      date: "March 2022 - Present",
      organization: "Jeju National University",
    }
  - {
      name: English Language for Software Engineering,
      date: "July 2022 â€“ August 2022",
      organization: "Auckland University of Technology",
    }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/NZ2.jpg"
  
  - image: "assets/images/portfolio/NZ3.jpg"

  - image: "assets/images/portfolio/NZ4.jpg"

  - image: "assets/images/portfolio/NZ5.jpg"

  - image: "assets/images/portfolio/Jeju1.jpg"

  - image: "assets/images/portfolio/Jeju3.jpg"

  - image: "assets/images/portfolio/Jeju4.jpg"
    
  - image: "assets/images/portfolio/Jeju7.jpg"



# Portfolio Page
portfolio-label:
  - { title: "Jeju", type: "Jeju" }
  - { title: "NewZealand", type: "NewZealand" }
  - { title: "Etc.", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/NZ1.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "NewZealand"

  - image: "assets/images/portfolio/NZ2.jpg"
    url: "#"
    portfolio-type:
      - type: "NewZealand"

  - image: "assets/images/portfolio/NZ3.jpg"
    url: "#"
    portfolio-type:
      - type: "NewZealand"

  - image: "assets/images/portfolio/NZ4.jpg"
    url: "#"
    portfolio-type:
      - type: "NewZealand"

  - image: "assets/images/portfolio/NZ5.jpg"
    url: "#"
    portfolio-type:
      - type: "NewZealand"


  - image: "assets/images/portfolio/Jeju1.jpg"
    url: "#"
    portfolio-type:
      - type: "Jeju"
 
  - image: "assets/images/portfolio/Jeju2.jpg"
    url: "#"
    portfolio-type:
      - type: "Jeju"
  
  - image: "assets/images/portfolio/Jeju3.jpg"
    url: "#"
    portfolio-type:
      - type: "Jeju"

  - image: "assets/images/portfolio/Jeju4.jpg"
    url: "#"
    portfolio-type:
      - type: "Jeju"

  - image: "assets/images/portfolio/Jeju5.jpg"
    url: "#"
    portfolio-type:
      - type: "Jeju"
  
  - image: "assets/images/portfolio/Jeju6.jpg"
    url: "#"
    portfolio-type:
      - type: "Jeju"
  
  - image: "assets/images/portfolio/Jeju7.jpg"
    url: "#"
    portfolio-type:
      - type: "Jeju"  


# Contact Section

contact-title: Contact Info
contact-email: cjm064@naver.com
